syntax = "proto3";

// Перечисление статусов бронирования.
enum BookingStatusEnumProto {
	// Статус ожидания подтверждения.
    Pending = 1;

	// Статус подтвержденного бронирования.
    Confirmed = 2;
}

// Сообщение бронирования.
message Booking
{
	int32 id = 1;
	google.protobuf.Timestamp startDate = 2;
	google.protobuf.Timestamp endDate = 3;
	int64 userId = 4;
	string userFirstName = 5;
	string userLastName = 6;
}

// Сообщение входной модели изменения статуса бронирования.
message ChangeBookingStatusRequest
{
	int32 bookingId = 1;
	BookingStatusEnumProto statusEnum = 2;
}

// Сообщение выходной модели изменения статуса бронирования.
message ChangeBookingStatusResponse
{
	Booking booking = 1;
}

// Сообщение входной модели получения статуса бронирования по Id.
message BookingStatusByBookingIdRequest
{
		int32 bookingId = 1;
}

// Сообщение входной модели создания бронирования. 
message CreateBookingRequest
{
	google.protobuf.Timestamp startDate = 1;
	google.protobuf.Timestamp endDate = 2;
}


// Сервис бронирования.
service BookingProtoService
{
	// Метод получает список бронирований.
	rpc GetBookings(google.protobuf.Empty) returns (BookingsResponse);

	// Метод обновляет статус бронирования.
	rpc ChangeBookingStatus(ChangeBookingStatusRequest) returns (ChangeBookingStatusResponse);

	// Метод оставляет заявку на возврат средств.
	rpc RefundPaymentBooking(RefundPaymentBookingRequest) returns(google.protobuf.Empty);

	// Метод удаляет бронирования, связанные с категориями.
	rpc RemoveBookingReletedCategories(RemoveBookingCategoryRequest) returns (google.protobuf.Empty);
}